version: "3.9"

services:
    db:
      image: postgres:latest
      restart: always
      env_file: 
          - .env
      ports:
          - "127.0.0.1:${DATABASE_PORT}:${DATABASE_PORT}"
      environment:
          - PGPORT=${DATABASE_PORT}
          - POSTGRES_DB=${DATABASE_NAME}
          - POSTGRES_USER=${DATABASE_USER}
          - POSTGRES_PASSWORD=${DATABASE_PASS}
      volumes:
        - ./data/db:/var/lib/postgresql/data

    web:
      build: .
      command: >
        sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
      ports:
        - "8000:8000"
      volumes:
        - .:/www
      depends_on:
        - db

    proxy:
      build:
        context: ./proxy
      restart: always
      depends_on:
        - web
      ports:
        - 8001:8000

