# Generated by Django 4.0.2 on 2022-02-12 12:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('boy', 'boy'), ('girl', 'girl')], max_length=20)),
                ('age', models.IntegerField()),
                ('type', models.CharField(choices=[('cat', 'cat'), ('dog', 'dog')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetsPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=300)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pets')),
            ],
        ),
        migrations.AddField(
            model_name='pets',
            name='photos',
            field=models.ManyToManyField(blank=True, to='api.PetsPhoto'),
        ),
    ]
