name: Docker Compose Actions Workflow
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: env
        run: |
          DATABASE_USER=${{secrets.DATABASE_USER}}
          DATABASE_PASS=${{secrets.DATABASE_PASS}}
          DATABASE_HOST=${{secrets.DATABASE_HOST}}
          DATABASE_PORT=${{secrets.DATABASE_PORT}}
          DATABASE_NAME=${{secrets.DATABASE_NAME}}
      - name: Build the stack
        run: docker-compose up -d web
      - name: Test
        run: docker-compose run web python manage.py test
