name: Docker Compose Actions Workflow
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    environment: pets-animals
    steps:
      - uses: actions/checkout@v2
      - name: create .nv file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG: false
          envkey_DATABASE_USER: ${{ secrets.DATABASE_USER}}
          envkey_DATABASE_PASS: ${{ secrets.DATABASE_PASS}}
          envkey_DATABASE_HOST: ${{ secrets.DATABASE_HOST}}
          envkey_DATABASE_PORT: ${{ secrets.DATABASE_PORT}}
          envkey_DATABASE_NAME: ${{ secrets.DATABASE_NAME}}
          envkey_ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS}}
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY}}
          envkey_API_HOST: ${{ secrets.API_HOST}}
          envkey_API_PORT: ${{ secrets.API_PORT}}
          envkey_API_KEY: ${{ secrets.API_KEY}}
          directory: /www/
          file_name: .env
          
      - name: Build the stack
        run: docker-compose up -d web
      - name: Test
        run: docker-compose run web python manage.py test
