name: Docker Compose Actions Workflow
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    environment: pets-animals
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d web
      - name: Test
        run: docker-compose run web python manage.py test
